# Generated by Django 5.0.6 on 2024-07-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('peso', models.FloatField()),
                ('dimensiones', models.CharField(max_length=50)),
                ('costo_envio', models.FloatField(blank=True, null=True)),
                ('fecha_despacho', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
